### ISSUE TITLE
geninfo format should use absolute file paths #2

### ISSUE THREAD

**Issue by Srinu461** [StevenLooman/mocha-lcov-reporter#15]
According to the geninfo page, the format is:
SF:

When i use the geninfo for creating .info file the SF:(absolute path of source file) is not updating for some of gcda files due to long path, is there any way to restrict to the geninfo take complete path with out missing any directory names between the path.

Can any one please help me on this ?

**Comment by StevenLooman** [comment]
Thank you for your issue. Is this `mocha-lcov-reporter` related, or is this something in general?

**Comment by Srinu461** [comment]
It is in general, geninfo not taking the absolute path (SF:<>) as the path is too long.
So please help on this

**Comment by Srinu461** [comment]
Can any one please explain about below while loop operation in perl script in detail.
Before while loop the Var variable is like below
$Var:/c/Platfrom_code/CISS/SwPf/trunk/_test/../../../../../../../../com/802_15_BT/BLE_Alpwise/Support/BLESW_CoreStack/Interfaces/AKU_340/AKU340_driver_cc.c
while ($result =~ s/\/[^\/]+\/\.\.\//\//)
{
}
After while loop Var variable is like below
$Var:/com/802_15_BT/BLE_Alpwise/Support/BLESW_CoreStack/Interfaces/AKU_340/AKU340_driver_cc.c

**Comment by StevenLooman** [comment]
I'm sorry, I can't really help you with this. `mocha-lcov-reporter` is solely for Javascript.

It seems, however, canonicalization is applied to your path.  The first part, `c/Platfrom_code/CISS/SwPf/trunk/_test` is stripped due to the `../../../../../../../..` right behind it. Whats left, is the part `/com/802_15_BT/BLE_Alpwise/Support/BLESW_CoreStack/Interfaces/AKU_340/AKU340_driver_cc.c`
